export const INCREMENT_BUTTON = "INCREMENT_BUTTON"
export const DECREMENT_BUTTON = "DECREMENT_BUTTON"
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION"
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION"